name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    
    - name: Install Dependencies
      run: npm install


    - name: Run Build
      run: npm run build
    
        
    - name: Run Production Scripts
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        USER: ${{ secrets.USER }}
        DATABASE: ${{ secrets.DATABASE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
        script: |
          cd ~/apps_nodejs/test-ci
          npm install
          pm2 restart server.js --watch
          
  
  
  
 


