name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
        
    - name: Run Production Scripts
      with:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        USER: ${{ secrets.USER }}
        DATABASE: ${{ secrets.DATABASE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
        script: |
          cd ~/apps_nodejs/test-ci
          npm install
          pm2 restart server.js --watch
          
  
  
  
 


