name: CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x 
          
      - name: Enter folder
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          database: ${{ secrets.DATABASE }}
          database_type: ${{ secrets.DATABASE_TYPE }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
        
      - name: Install dependencies
        run: |
          cd apps_nodejs/test-ci
          npm install
          
        
      - name: Start Server
        run: node index.js
