name: CI

on:
  push:
    branches: [ main ]

env:
  CI: true
  host: ${{ secrets.HOST }}
  port: ${{ secrets.PORT }}
  database: ${{ secrets.DATABASE }}
  database_type: ${{ secrets.DATABASE_TYPE }}
  user: ${{ secrets.USER }}
  password: ${{ secrets.PASSWORD }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      
      # Setup Node JS
      - uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
          
      - name: Enter folder
        run: cd /apps_nodejs/test-ci
        
      - name: Install dependencies
        run: npm install
          
      - name: Start Server
        run: node index.js
