name: CI

on:
  push:
    branches: [ main ]

jobs:

  deploy-dev:
  runs-on: ubuntu-latest

  steps:
    - name: Dev
      run: echo Deploy Dev!

  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      
      # Setup Node JS
      - uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
          
      - name: Install and Start Aplication
        uses: appleboy/ssh-action@master
        environment: production
        needs: [deploy-dev]
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          database: ${{ secrets.DATABASE }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          database_type:  ${{ secrets.DATABASE_TYPE }}
          script: |
            cd ~/quiz
            npm install
            pm2 restart index.js --watch
  
