name: CI

on:
  push:
    branches: [ main ]

jobs:

  # VERIFY .env
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".env"

      - name: File exists
        uses: SpicyPizza/create-envfile@v1
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          envkey_APP_HOST: ${{ secrets.APP_HOST }}
          envkey_APP_PORT: ${{ secrets.APP_PORT }}

          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
          file_name: .env
  
  # TEST DEPLOY
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Dev
        run: echo Deploy Dev!

  # DEPLOY PRODUCTION
  deploy-production:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    environment:
      name: production

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
           node-version: 12.x

      - name: Create EnvFile in Prod
      - uses: actions/checkout@v2
      - run: echo Verify .env
        if: steps.check.outputs.exists == 'false'
      - run: echo "Write a file to S3 bucket with name \${GITHUB_SHA}"
        if: steps.check.outputs.exists == 'false'
          
      - name: Install and Start Aplication
        # uses: appleboy/ssh-action@master
      - uses: actions/checkout@v2

        with:
          script: |
            cd ~/test-ci
            npm install
            cd ..
            pm2 start test-ci --watch
  
