name: CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      
      # Setup Node JS
      - uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
          
      - name: Install and Start Aplication
        uses: appleboy/ssh-action@master
        with:
          CI: true
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          database: ${{ secrets.DATABASE }}
          database_type: ${{ secrets.DATABASE_TYPE }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/apps_nodejs/test-ci
            npm install
            pm2 restart index.js --watch
