name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  USER: ${{ secrets.USER }}
  DATABASE: ${{ secrets.DATABASE }}
  PASSWORD: ${{ secrets.PASSWORD }}
  DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Project Install
        run: npm install

    - name: Project Start prod
        run: npm run build
        
